name: CI Sistem Maklumat Pelajar

on:
  push:
    branches:
      - main

jobs:

  ujian:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Jalankan Ujian
        run: npm test
